# Generated by Django 5.2.8 on 2025-11-19 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('pull_request_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pull_request_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MERGED', 'Merged')], default='OPEN', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_prs', to='api.user')),
                ('reviewers', models.ManyToManyField(blank=True, related_name='assigned_prs', to='api.user')),
            ],
        ),
    ]
