# Generated by Django 5.2.8 on 2025-11-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullrequest',
            old_name='updated_at',
            new_name='merged_at',
        ),
    ]
